"""make_school_fields_nullable

Revision ID: 3a25955598d6
Revises: 7d6f71fdf36e
Create Date: 2025-02-03 15:38:58.733787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a25955598d6'
down_revision: Union[str, None] = '7d6f71fdf36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'year_range',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'year_range',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
