"""remove unneeded suburb columns

Revision ID: a8c8e443a43f
Revises: e47bb284ceac
Create Date: 2025-02-03 21:53:39.347920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c8e443a43f'
down_revision: Union[str, None] = 'e47bb284ceac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suburb', 'latitude')
    op.drop_column('suburb', 'longitude')
    op.drop_column('suburb', 'auction_clearance_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suburb', sa.Column('auction_clearance_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('suburb', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('suburb', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
